// ignore_for_file: depend_on_referenced_packages

import 'package:path/path.dart' as p;

class UrlTypeHelper {
  static final List<String> imageTypes = [
    'jpg',
    'jpeg',
    'jfif',
    'pjpeg',
    'pjp',
    'png',
    'svg',
    'gif',
    'apng',
    'webp',
    'avif',
  ];

  static final List<String> videoTypes = [
    "3g2",
    "3gp",
    "aaf",
    "asf",
    "avchd",
    "avi",
    "drc",
    "flv",
    "m2v",
    "m3u8",
    "m4p",
    "m4v",
    "mkv",
    "mng",
    "mov",
    "mp2",
    "mp4",
    "mpe",
    "mpeg",
    "mpg",
    "mpv",
    "mxf",
    "nsv",
    // "ogg",
    "ogv",
    "qt",
    "rm",
    "rmvb",
    "roq",
    "svi",
    "vob",
    "webm",
    "wmv",
    "yuv",
  ];

  // static final List<String> voiceTypes = [
  //   "mp3",
  //   "m4a",
  //   "m4b",
  //   "m4p",
  //   "mmf",
  //   "aa",
  //   "aac",
  //   "aax",
  //   "amr",
  //   "movpkg",
  //   '3ga',
  //   'ac3',
  //   'aiff',
  //   'ape',
  //   'au',
  //   'flac',
  //   'mid',
  //   'mpc',
  //   'oga',
  //   'ogg',
  //   'opus',
  //   'ra',
  //   'wav',
  //   'wma',
  //   'wv',
  // ];

  static final List<String> voiceTypes = [
    "mp3",
    "wav",
    "aac",
    "flac",
    "aiff",
    "ogg",
    "wma",
    "midi",
    "amr",
    "alac",
    "pcm",
    "dsd",
    "ape",
    "ac3",
    "m4a",
    "opus",
    "speex",
    "vox",
    "wv",
    "tak",
    "mpc",
    "tta",
    "dts",
    "au",
    "ra",
    "rm",
    "mka",
    "mpeg-4",
    "mpeg-2",
    "mpeg-1",
    "mpeg-7",
    "mpeg-21",
    "mpeg-4 part 14",
    "mpeg-4 part 12",
    "mpeg-4 part 10",
    "mpeg-4 part 3",
    "mpeg-4 part 2",
    "mpeg-4 part 1",
    "mpeg-4 audio",
    "mpeg-4 avc",
    "mpeg-4 asp",
    "mpeg-4 aac",
    "mpeg-4 he-aac",
    "mpeg-4 bsac",
    "mpeg-4 celp",
    "mpeg-4 hvxc",
    "mpeg-4 er-aac",
    "mpeg-4 er-bsac",
    "mpeg-4 er-celp",
    "mpeg-4 er-hvxc",
    "mpeg-4 er-lbr",
    "mpeg-4 er-ld",
    "mpeg-4 er-mlp",
    "mpeg-4 er-ps",
    "mpeg-4 er-sbr",
    "mpeg-4 er-sld",
    "mpeg-4 er-td",
    "mpeg-4 er-usac",
    "mpeg-4 er-vm",
    "mpeg-4 er-xmt",
    "mpeg-4 er-3d audio",
    "mpeg-4 er-bsac",
    "mpeg-4 er-celp",
    "mpeg-4 er-hvxc",
    "mpeg-4 er-lbr",
    "mpeg-4 er-ld",
    "mpeg-4 er-mlp",
    "mpeg-4 er-ps",
    "mpeg-4 er-sbr",
    "mpeg-4 er-sld",
    "mpeg-4 er-td",
    "mpeg-4 er-usac",
    "mpeg-4 er-vm",
    "mpeg-4 er-xmt",
    "mpeg-4 er-3d audio",
  ];

  // static final List<String> fileTypes = [
  //   'txt',
  //   'pdf',
  //   'doc',
  //   'docx',
  //   'xls',
  //   'xlsx',
  //   'ppt',
  //   'pptx',
  //   'html',
  //   'css',
  //   'js',
  //   'json',
  //   'xml',
  //   'csv',
  //   'png',
  //   'jpg',
  //   'jpeg',
  //   'gif',
  //   'bmp',
  //   'tiff',
  //   'mp3',
  //   'wav',
  //   'flac',
  //   'aac',
  //   'ogg',
  //   'mp4',
  //   'avi',
  //   'mkv',
  //   'mov',
  //   'wmv',
  //   'zip',
  //   'rar',
  //   'tar',
  //   'gz',
  //   '7z',
  // ];

  static final List<String> fileTypes = [
    "txt",
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    "csv",
    "rtf",
    "html",
    "xml",
    "json",
    "zip",
    "rar",
    "7z",
    "tar",
    "gz",
    "bz2",
    "dmg",
    "iso",
    "img",
    "exe",
    "apk",
    "app",
    "deb",
    "rpm",
    "jar",
    "mp3",
    "wav",
    "aac",
    "flac",
    "aiff",
    // "ogg",
    "wma",
    "midi",
    "amr",
    "alac",
    "pcm",
    "dsd",
    "ape",
    "ac3",
    "m4a",
    "opus",
    "speex",
    "vox",
    "wv",
    "tak",
    "mpc",
    "tta",
    "dts",
    "au",
    "ra",
    "rm",
    "mka",
    "mpeg-4",
    "mpeg-2",
    "mpeg-1",
    "mpeg-7",
    "mpeg-21",
    "mpeg-4 part 14",
    "mpeg-4 part 12",
    "mpeg-4 part 10",
    "mpeg-4 part 3",
    "mpeg-4 part 2",
    "mpeg-4 part 1",
    "mpeg-4 audio",
    "mpeg-4 avc",
    "mpeg-4 asp",
    "mpeg-4 aac",
    "mpeg-4 he-aac",
    "mpeg-4 bsac",
    "mpeg-4 celp",
    "mpeg-4 hvxc",
    "mpeg-4 er-aac",
    "mpeg-4 er-bsac",
    "mpeg-4 er-celp",
    "mpeg-4 er-hvxc",
    "mpeg-4 er-lbr",
    "mpeg-4 er-ld",
    "mpeg-4 er-mlp",
    "mpeg-4 er-ps",
    "mpeg-4 er-sbr",
    "mpeg-4 er-sld",
    "mpeg-4 er-td",
    "mpeg-4 er-usac",
    "mpeg-4 er-vm",
    "mpeg-4 er-xmt",
    "mpeg-4 er-3d audio",
    "mpeg-4 er-bsac",
    "mpeg-4 er-celp",
    "mpeg-4 er-hvxc",
    "mpeg-4 er-lbr",
    "mpeg-4 er-ld",
    "mpeg-4 er-mlp",
    "mpeg-4 er-ps",
    "mpeg-4 er-sbr",
    "mpeg-4 er-sld",
    "mpeg-4 er-td",
    "mpeg-4 er-usac",
    "mpeg-4 er-vm",
    "mpeg-4 er-xmt",
    "mpeg-4 er-3d audio",
  ];

  static final List<String> supportedFileTypes = [
  ///files
  "pdf",
  "doc",
  "docx",
  "xls",
  "xlsx",
  "ppt",
  "pptx",
  ];

  static final List<String> capedFileTypes = [
    ///files
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    /// photos
    'jpg',
    'jpeg',
    'jfif',
    'pjpeg',
    'pjp',
    'png',
    'svg',
    'gif',
    'apng',
    'webp',
    'avif',
    ///videos
    "3g2",
    "3gp",
    "aaf",
    "asf",
    "avchd",
    "avi",
    "drc",
    "flv",
    "m2v",
    "m3u8",
    "m4p",
    "m4v",
    "mkv",
    "mng",
    "mov",
    "mp2",
    "mp4",
    "mpe",
    "mpeg",
    "mpg",
    "mpv",
    "mxf",
    "nsv",
    // "ogg",
    "ogv",
    "qt",
    "rm",
    "rmvb",
    "roq",
    "svi",
    "vob",
    "webm",
    "wmv",
    "yuv",
    /// voices
    "mp3",
    "wav",
    "aac",
    "flac",
    "aiff",
    "ogg",
    "wma",
    "midi",
    "amr",
    "alac",
    "pcm",
    "dsd",
    "ape",
    "ac3",
    "m4a",
    "opus",
    "speex",
    "vox",
    "wv",
    "tak",
    "mpc",
    "tta",
    "dts",
    "au",
    "ra",
    "rm",
    "mka",
    "mpeg-4",
    "mpeg-2",
    "mpeg-1",
    "mpeg-7",
    "mpeg-21",
    "mpeg-4 part 14",
    "mpeg-4 part 12",
    "mpeg-4 part 10",
    "mpeg-4 part 3",
    "mpeg-4 part 2",
    "mpeg-4 part 1",
    "mpeg-4 audio",
    "mpeg-4 avc",
    "mpeg-4 asp",
    "mpeg-4 aac",
    "mpeg-4 he-aac",
    "mpeg-4 bsac",
    "mpeg-4 celp",
    "mpeg-4 hvxc",
    "mpeg-4 er-aac",
    "mpeg-4 er-bsac",
    "mpeg-4 er-celp",
    "mpeg-4 er-hvxc",
    "mpeg-4 er-lbr",
    "mpeg-4 er-ld",
    "mpeg-4 er-mlp",
    "mpeg-4 er-ps",
    "mpeg-4 er-sbr",
    "mpeg-4 er-sld",
    "mpeg-4 er-td",
    "mpeg-4 er-usac",
    "mpeg-4 er-vm",
    "mpeg-4 er-xmt",
    "mpeg-4 er-3d audio",
    "mpeg-4 er-bsac",
    "mpeg-4 er-celp",
    "mpeg-4 er-hvxc",
    "mpeg-4 er-lbr",
    "mpeg-4 er-ld",
    "mpeg-4 er-mlp",
    "mpeg-4 er-ps",
    "mpeg-4 er-sbr",
    "mpeg-4 er-sld",
    "mpeg-4 er-td",
    "mpeg-4 er-usac",
    "mpeg-4 er-vm",
    "mpeg-4 er-xmt",
    "mpeg-4 er-3d audio",
  ];

  static UrlType getType(url) {
    try {
      Uri uri = Uri.parse(url);
      String extension = p.extension(uri.path).toLowerCase();
      if (extension.isEmpty) {
        if(url.contains("youtube.com")){
          return UrlType.youtube;
        }
        return UrlType.unknown;
      }
      extension = extension.split('.').last;
      if (imageTypes.contains(extension)) {
          if(url.contains("http")){
            return UrlType.image;
          }
        return UrlType.memoryImage;
      } else if (videoTypes.contains(extension)) {
        return UrlType.video;
      }  else if (voiceTypes.contains(extension)) {
        return UrlType.voice;
      } else if (fileTypes.contains(extension)) {
        return UrlType.file;
      }
    } catch (e) {
      return UrlType.unknown;
    }
    return UrlType.unknown;
  }
}

enum UrlType {
  image,
  memoryImage,
  youtube,
  video,
  voice,
  file,
  unknown,
}
